// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasteleriaNancys.Infrastructure.Data;

#nullable disable

namespace PasteleriaNancys.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706174842_AgregarInsumosPersonalizacionPedido")]
    partial class AgregarInsumosPersonalizacionPedido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.GastoExtra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdGasto");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdTurno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdTurno");

                    b.ToTable("Gasto_Extra", "Caja");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdTurno");

                    b.Property<decimal?>("DiferenciaArqueo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdUsuarioResponsable")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuario_Responsable");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalGastosExtras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalIngresosSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("Turno", "Caja");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.VentaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdDetalle");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("IdItem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVenta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdVenta");

                    b.ToTable("Venta_Detalle", "Caja");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.VentaPos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdVenta");

                    b.Property<bool>("Anulada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdTurno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdTurno");

                    b.ToTable("Venta_POS", "Caja");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.EventoFestivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdEvento");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("MultiplicadorDemanda")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Evento_Festivo", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.ItemCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdItem");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CodigoReferencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioUnitario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReferencia")
                        .IsUnique();

                    b.ToTable("Item_Catalogo", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.LotePeps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdLote");

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Óptimo");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaElaboracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("IdItem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdProveedor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Lote_PEPS", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.LotePepsOrdenado", b =>
                {
                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("CantidadInicial")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("CodigoReferencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiasParaCaducar")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaElaboracion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdItem")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLote")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrdenConsumo")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_Lotes_PEPS_Ordenados", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdProveedor");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Proveedor", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.RecetaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdReceta");

                    b.Property<decimal>("CantidadRequerida")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("IdItemInsumo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdItemTerminado")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdItemInsumo");

                    b.HasIndex("IdItemTerminado", "IdItemInsumo")
                        .IsUnique();

                    b.ToTable("Receta_Item", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.StockMinimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdStockMinimo");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("CantidadMinima")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("IdItem")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdItem")
                        .IsUnique();

                    b.ToTable("Stock_Minimo", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.ViajeDespacho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdViaje");

                    b.Property<string>("Conductor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Programado");

                    b.Property<DateTime>("FechaDespacho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("IdUsuarioConductor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuario_Conductor");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Viaje_Despacho", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.ViajeDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdDetalle");

                    b.Property<decimal>("CantidadEnviada")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("IdLote")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdViaje")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdLote");

                    b.HasIndex("IdViaje");

                    b.ToTable("Viaje_Detalle", "Inventario");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Pedidos.PagoQr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPago");

                    b.Property<string>("CanalPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoRespuestaBanco")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaGeneracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("MontoConfirmado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoSolicitado")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido");

                    b.ToTable("Pago_QR", "Web");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Pedidos.PedidoCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdPedido");

                    b.Property<string>("CodigoQrReferencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CodigoQR_Referencia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente QR");

                    b.Property<DateTime>("FechaEntregaSolicitada")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaEntrega_Solicitada");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("IdUsuarioVendedora")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuario_Vendedora");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalCotizado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Pedido_Cliente", "Web");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Pedidos.PedidoConfiguracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdConfiguracion");

                    b.Property<string>("ColorDecoracion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DedicatoriaDetalle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Dedicatoria_Detalle");

                    b.Property<Guid?>("IdInsumoRelleno")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdInsumo_Relleno");

                    b.Property<Guid?>("IdInsumoSaborMasa")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdInsumo_SaborMasa");

                    b.Property<Guid?>("IdItemProductoBase")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdItem_ProductoBase");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagenReferenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ImagenReferencia_URL");

                    b.Property<decimal?>("PorcentajeAnticipo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Porcentaje_Anticipo");

                    b.Property<string>("SaborMasa")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TamanoRacion")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoRelleno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido")
                        .IsUnique();

                    b.ToTable("Pedido_Configuracion", "Web");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Seguridad.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", "Seguridad");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Vendedora"
                        },
                        new
                        {
                            IdRol = 3,
                            Nombre = "Encargado de Almacen"
                        });
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Seguridad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdUsuario");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario", "Seguridad");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.GastoExtra", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Caja.Turno", "Turno")
                        .WithMany("GastosExtra")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.VentaDetalle", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Caja.VentaPos", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.VentaPos", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Caja.Turno", "Turno")
                        .WithMany("VentasPos")
                        .HasForeignKey("IdTurno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.LotePeps", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Inventario.ItemCatalogo", "Item")
                        .WithMany("LotesPeps")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PasteleriaNancys.Domain.Inventario.Proveedor", "Proveedor")
                        .WithMany("LotesPeps")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Item");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.RecetaItem", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Inventario.ItemCatalogo", "ItemInsumo")
                        .WithMany()
                        .HasForeignKey("IdItemInsumo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PasteleriaNancys.Domain.Inventario.ItemCatalogo", "ItemTerminado")
                        .WithMany()
                        .HasForeignKey("IdItemTerminado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemInsumo");

                    b.Navigation("ItemTerminado");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.StockMinimo", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Inventario.ItemCatalogo", "Item")
                        .WithMany()
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.ViajeDetalle", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Inventario.LotePeps", "Lote")
                        .WithMany()
                        .HasForeignKey("IdLote")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PasteleriaNancys.Domain.Inventario.ViajeDespacho", "Viaje")
                        .WithMany("Detalles")
                        .HasForeignKey("IdViaje")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Viaje");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Pedidos.PagoQr", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Pedidos.PedidoCliente", "Pedido")
                        .WithMany("PagosQr")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Pedidos.PedidoConfiguracion", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Pedidos.PedidoCliente", "Pedido")
                        .WithOne("Configuracion")
                        .HasForeignKey("PasteleriaNancys.Domain.Pedidos.PedidoConfiguracion", "IdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Seguridad.Usuario", b =>
                {
                    b.HasOne("PasteleriaNancys.Domain.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.Turno", b =>
                {
                    b.Navigation("GastosExtra");

                    b.Navigation("VentasPos");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Caja.VentaPos", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.ItemCatalogo", b =>
                {
                    b.Navigation("LotesPeps");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.Proveedor", b =>
                {
                    b.Navigation("LotesPeps");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Inventario.ViajeDespacho", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Pedidos.PedidoCliente", b =>
                {
                    b.Navigation("Configuracion");

                    b.Navigation("PagosQr");
                });

            modelBuilder.Entity("PasteleriaNancys.Domain.Seguridad.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
